# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fc3d7fe7d18b321d2e53fd150f8f74a427b7ad83e7e4a39082b6c7fe9efb89cf5644354047a84a2c8c94fc7aa9cf5e981f73613961f71a144fb7661a57e9cdd

test:
  secret_key_base: c8b3e6da00c264d5e317bbaedbf5e858a0d33c5abf3543c13d234ac34671c81c2a91b93297183b1ab97138f7e3fd25c317d9701fd7e6d646d14c96b081bbd0b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
